services:
  osm2gazebo:
    build: .
    image: osm2gazebo:latest
    container_name: osm2gazebo
    working_dir: /app
    volumes:
      - ./maps:/maps
      - .:/app
    environment:
      - OSM2WORLD_JAR=/opt/osm2world/OSM2World.jar
      - GAZEBO_MODEL_PATH=/maps:/usr/share/gazebo-11/models
      - JAVA_TOOL_OPTIONS=-Djava.awt.headless=true
    tty: true
    
  # Development environment with Gazebo Garden
  dev:
    build: .
    image: osm2gazebo:latest
    container_name: osm2gazebo-dev
    working_dir: /app
    volumes:
      - ./maps:/maps
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - OSM2WORLD_JAR=/opt/osm2world/OSM2World.jar
      - DISPLAY=${DISPLAY}
      - GAZEBO_MODEL_PATH=/maps:/usr/share/gz/models
      - GZ_SIM_RESOURCE_PATH=/maps:/usr/share/gz/models
      - JAVA_TOOL_OPTIONS=-Djava.awt.headless=true
    tty: true


